// Cucumber.js configuration (CommonJS so it loads regardless of "type": "module").
// TypeScript step definitions are loaded through the tsx ESM loader, wired via
// NODE_OPTIONS="--import tsx" in the `test:bdd` npm script.
//
// `paths` intentionally lists only the features that have been IMPLEMENTED. The
// drafts for later priorities (0002–0008) stay untouched and are added here as
// each one is built to green, in priority order.
module.exports = {
  default: {
    paths: [
      "docs/features/0001-vault-wall-isolation.feature",
      "docs/features/0002-event-visibility-and-propagation.feature",
      "docs/features/0003-behavioral-fidelity.feature",
      "docs/features/0004-replayability-and-naming.feature",
      "docs/features/0005-competition-eligibility.feature",
      "docs/features/0006-outcomes-by-stats-and-temperature.feature",
      "docs/features/0007-persistence-non-degradation.feature",
      "docs/features/0008-daily-event-invariant.feature",
      "docs/features/0009-mcp-tool-boundary.feature",
      "docs/features/0011-weekly-loop-orchestration.feature",
      "docs/features/0012-conversation-and-scene-system.feature",
      "docs/features/0013-diary-room.feature",
      "docs/features/0014-jury-and-endgame.feature",
      "docs/features/0015-character-creation-oobe.feature",
      "docs/features/0016-god-mode-admin.feature",
      "docs/features/0017-relationship-model.feature",
      "docs/features/0018-narrative-moment-orchestration.feature",
      "docs/features/0019-agent-driven-play-loop.feature",
      "docs/features/0020-player-experience.feature",
      "docs/features/0021-game-session-and-save-lifecycle.feature",
      "docs/features/0023-consequence-and-memory.feature",
      "docs/features/0024-soul-storage-and-memory-recall.feature",
      "docs/features/0025-reserve-twists.feature",
      "docs/features/0026-relationship-math.feature",
      "docs/features/0027-narrative-port-llm-adapter.feature",
      "docs/features/0028-temperature-and-emotional-constants.feature",
      "docs/features/0030-durable-game-persistence-survive-restart.feature",
      "docs/features/0031-game-orchestrator-and-integrity-watcher.feature",
      "docs/features/0034-live-weekly-progression-and-decision-seam.feature",
      "docs/features/0037-live-jury-vote-choreography.feature",
      "docs/features/0038-live-offscreen-society.feature",
      "docs/features/0039-promise-and-deal-tracking.feature",
      "docs/features/0040-npc-confessionals.feature",
      "docs/features/0041-character-evolution-and-arc.feature",
      "docs/features/0042-competition-library.feature",
      "docs/features/0043-emergent-bloc-behavior.feature",
      "docs/features/0044-strategic-nomination-and-vote-refinements.feature",
      "docs/features/0045-endgame-structure.feature",
      "docs/features/0046-player-eviction-and-jury.feature",
      "docs/features/0047-eviction-night-live.feature",
      "docs/features/0048-season-retrospective-and-unsealing.feature",
      "docs/features/0049-house-presence-and-lingering.feature",
      "docs/features/0050-casting-interview.feature",
      "docs/features/0058-deep-character-profiles.feature",
      "docs/features/0060-story-thread-scheduler.feature",
      "docs/features/0061-player-self-eviction.feature",
      "docs/features/0063-casting-diversity-floor.feature",
      "docs/features/0062-world-snapshot-zeitgeist.feature",
      "docs/features/0065-cast-prewarm.feature",
      "docs/features/0066-in-game-time-and-sleep.feature",

      "docs/features/0070-offscreen-texture-enrichment.feature",
      "docs/features/0071-defensive-hardening-redaction-url-guards.feature",
      "docs/features/0072-multi-platform-gateway.feature",
      "docs/features/0073-structural-anti-sycophancy-wall.feature",
      "docs/features/0075-trust-gated-confidences.feature",
      "docs/features/0077-house-map-privacy-and-eyeshot.feature",
      "docs/features/0078-motivated-society-and-intentional-movement.feature",
      "docs/features/0084-character-voice-and-mood.feature",
      "docs/features/0085-npc-campaigns-and-the-scramble.feature",
      "docs/features/0086-houseguest-drives.feature",
      "docs/features/0087-relationship-trajectories.feature",
      "docs/features/0088-living-current-read.feature",
      "docs/features/0089-reactive-confessionals.feature",
      "docs/features/0091-trigger-secrets-house-events.feature",
      "docs/features/0092-secret-pacing-drip.feature",
      "docs/features/0093-secrets-as-levers.feature",
      "docs/features/0099-secrets-as-currency.feature",
      "docs/features/0094-distorted-gossip-consequences.feature",
      "docs/features/0095-pre-show-ties-reveal.feature",
      "docs/features/0096-emergent-nemesis.feature",
      "docs/features/0100-jury-grudge-book.feature",
      "docs/features/0101-npc-myth-making.feature",
      "docs/features/0104-season-notoriety.feature",
      "docs/features/0105-suspicion-and-mood-anchoring.feature",
      "docs/features/0109-deal-duration.feature",
      "docs/features/0110-vote-deduction.feature",
      "docs/features/0111-day-1-experience.feature",
      "docs/features/0115-diary-room-strategic-confessional.feature",
      "docs/features/0116-model-authored-cast-genesis.feature",
      "docs/features/0117-house-lives-in-in-game-time.feature",
      "docs/features/0118-ceremonies-as-timed-interrupts.feature",
      "docs/features/0119-per-event-felt-durations.feature",
      "docs/features/0120-strategic-drive-offscreen-cadence.feature",
      "docs/features/0121-deal-depth-kinds-and-reliability-rewards.feature",
      "docs/features/0122-deeper-daily-npc-confessionals.feature",
      "docs/features/0123-npc-initiated-deal-offers.feature",
      "docs/features/0124-deeper-character-evolution.feature",
      "docs/features/0125-competition-theme-variety.feature",
    ],
    import: ["features/support/**/*.ts", "features/step_definitions/**/*.ts"],
  },
};
