# shellcheck shell=bash
#
# orwell — the deploy OPT-IN feature-flag defaults, in ONE place.
#
# This is the SINGLE SOURCE of the set of env vars the deploy opts into on top of the engine's
# code defaults. It is SOURCED (never executed) by BOTH:
#   • deploy/orwell-install.sh  — writes the whole set into a FRESH box's data/.env (write_config).
#   • deploy/orwell-update.sh   — BACKFILLS any of these MISSING from an existing box's data/.env
#                                 (add-if-absent, never-clobber), so a box provisioned before a flag
#                                 was added still gains it on its next update.
#
# Why this file exists: every flag below DEFAULTS OFF in engine code (so the seeded calibration + the
# 0108 golden fixture stay byte-identical) and is turned ON only by the deploy. The installer used to
# hand-write them and the updater reconciled NONE of them — so an old box permanently missed whatever
# flag post-dated it (the one that got noticed: ORWELL_EMBEDDINGS unset ⇒ the engine silently runs
# DEGRADED deterministic semantic recall). Keeping the (KEY, DEFAULT) truth here means the two scripts
# cannot drift: add or change a flag in THIS file only and both the install and the backfill pick it up.
#
# The list is deploy OPT-IN FEATURE flags ONLY — it deliberately excludes the REQUIRED infra vars
# (ORWELL_ENGINE_TOKEN / _ADMIN_TOKEN / _MCP_URL / _PORT, ORWELL_PORT, ORWELL_DATA_DIR, ORWELL_BIND_HOST,
# ORWELL_ENGINE_MULTIUSER, OPENAI_API_KEY, LLM_HOSTS), which already exist on any running box and must
# never be regenerated by a reconcile (a fresh token would kill auth).
#
# Per-flag rationale (kept here as SOURCE comments — deliberately NOT emitted into data/.env, so the
# installer's written .env stays byte-identical to its historical hand-written block, and the updater's
# add-if-absent loop only ever sees real KEY=VALUE lines — see orwell_optin_env_defaults below):
#   ORWELL_EMBEDDINGS / ORWELL_EMBED_CACHE  Semantic recall (ADR 0004 / E86a): the REAL local-ONNX
#       fastembed provider (version-pinned; model prefetched into <data_dir>/models, offline thereafter).
#       Missing ⇒ the engine falls back to DEGRADED deterministic recall.
#   ORWELL_CAMPAIGNS            NPC strategic-campaign layer (0085) — hidden agendas tilting noms/votes.
#   ORWELL_TRAJECTORIES         Relationship arcs curdling (0087).
#   ORWELL_TRIGGERS             Trigger secrets erupting (0091).
#   ORWELL_SECRET_PACING        Dormant-secret paced drip (0092).
#   ORWELL_JURY_HOUSE           Jury grudges accumulating (0100).
#   ORWELL_TRAITORS_FURY        Jury bearing thresholds (#1790).
#   ORWELL_PRODUCER_READ        Post-scene exchange accounting (#1792).
#   ORWELL_SEEDED_TIE_SURFACING Seeded pre-show ties surfacing (0059 §5).
#       (The five above are the B2 2026-07-05 "living house" activation; the God-Mode "Living house"
#        dial overrides them per-sandbox at runtime, and /health's `flags` block reports the boot state.)
#   ORWELL_STRATEGIC_CADENCE    Strategic-drive off-screen cadence (0120) — sharper NPCs scheme a touch more.
#   ORWELL_SCHEME_TARGETS       Off-screen scheming names a real third-party target (Wave-2 fidelity) — the
#       initiator's strongest threat read is named in the HIDDEN scene; reaches the player only via gossip.
#       Vault-safe (side rng, no number) — the seeded comp/vote spine is byte-identical even while ON.
#   ORWELL_CONFESSIONAL_DEPTH   Deeper daily NPC confessionals (0122) — Vault-only, clock-gated.
#   ORWELL_DEAL_DEPTH           Deal depth (0121) — comp-throw / veto-save deals + reliability rewards.
#   ORWELL_NPC_DEAL_OFFERS      NPC-initiated deal offers (0123) — a motivated NPC floats a deal at a lull.
#   ORWELL_SOUL_DEPTH           Deeper character evolution (0124) — hidden layer; CHARACTER byte-stable.
#   ORWELL_COMP_MECHANICS_PLUS  Expanded competition mechanics (0126) — 12 => 30 no-repeat pool.
#   ORWELL_COMP_MIXED           Mixed-type/HYBRID competitions (0127) — secondary aptitude blended (65/35).
#   ORWELL_COMP_INTENT          NPC competition intent (0006b) — derived compete/throw/play-safe.
#   ORWELL_MYTH_MAKING          NPC myth-making (0101) — a rare notable player act becomes house folklore
#       and diffuses NPC-to-NPC (owner ruling 2026-07-17: on). Hidden-knowledge layer only; own isolated
#       rng, folds NO relationship edge — the seeded comp/vote spine is byte-identical even while ON.
#   ORWELL_VOTE_DEDUCTION       Vote deduction (0110) — the jury grudge book reasons about who voted how
#       (owner ruling 2026-07-17: on). Self-gated: absent/off ⇒ the grudge folds the true votes exactly
#       as before (no deduction, no sub-rng) — the seeded jury spine is unmoved.
#   ORWELL_GOSSIP_DRIFT         Character-mediated gossip drift (#1397) — owner ruling Q2 (2026-07-21,
#       #1779: docs/design/2026-07-21-moonshot-round2-divergent-slate.md §5). With it unset the
#       orchestrator passes no `voiceOf` to `diffuseGossip` (personality-agnostic drift, byte-identical
#       to the pre-feature behavior); ON, the reteller's own voice colors the distortion. Drift is
#       re-weighted on a per-hop FORK regardless, so the seeded comp/vote/jury draw stream is
#       byte-identical either way — see `gossip.ts:180-358`.
#   ORWELL_SECRET_BARTER        Off-screen NPC<->NPC secret barter (0099 hidden half) — owner ruling Q2
#       (2026-07-21, #1779). With it unset `secretBarterTick` returns before drawing anything (the
#       dedicated barter-rng stream never advances, no secret changes hands) — the seeded comp/vote/jury
#       spine is byte-identical — see `secretBarterConstants.ts:14-18`.
#   ORWELL_SHOWRUNNER           AI Showrunner (0101/#1401) Phase-1 ONLY — owner ruling Q2 (2026-07-21,
#       #1779: "Phase-1 observe-only; REWEIGHT stays off"). Phase-1 composes on a pure scoring pass (no
#       rng) and only routes an emphasized surfaced thread's belief to the player, fold-free — the
#       seeded comp/vote/jury spine is byte-identical even while ON. The OUTCOME-AFFECTING sibling
#       `ORWELL_SHOWRUNNER_REWEIGHT` (Phase-2, #1455) is DELIBERATELY NOT added here and MUST stay
#       unset — it re-orders the scheduler and folds hidden relationship weights, so it is NOT
#       calibration-neutral and is explicitly out of scope for #1779 — see `GameSessionAdapter.ts:610-640`.

# orwell_optin_env_defaults <data_dir>
#   Prints the opt-in KEY=VALUE lines — ONLY bare KEY=VALUE, one per line, in the installer's historical
#   order (no comments, so install's .env stays byte-identical and update's add-if-absent loop is clean).
#   <data_dir> is the box's data/ directory: orwell-install.sh passes ${DATA_DIR} (== ${APP_DIR}/data),
#   orwell-update.sh passes ${APP_DIR}/data — the same dir the model prefetch warms — so ORWELL_EMBED_CACHE
#   resolves to the same <data_dir>/models in both paths.
orwell_optin_env_defaults() {
  local data_dir="${1:?orwell_optin_env_defaults: data_dir argument required}"
  cat <<EOF
ORWELL_EMBEDDINGS=fastembed
ORWELL_EMBED_CACHE=${data_dir}/models
ORWELL_CAMPAIGNS=1
ORWELL_TRAJECTORIES=1
ORWELL_TRIGGERS=1
ORWELL_SECRET_PACING=1
ORWELL_JURY_HOUSE=1
ORWELL_SEEDED_TIE_SURFACING=1
ORWELL_STRATEGIC_CADENCE=1
ORWELL_SCHEME_TARGETS=1
ORWELL_CONFESSIONAL_DEPTH=1
ORWELL_DEAL_DEPTH=1
ORWELL_NPC_DEAL_OFFERS=1
ORWELL_SOUL_DEPTH=1
ORWELL_COMP_MECHANICS_PLUS=1
ORWELL_COMP_MIXED=1
ORWELL_COMP_INTENT=1
ORWELL_MYTH_MAKING=1
ORWELL_VOTE_DEDUCTION=1
ORWELL_GOSSIP_DRIFT=1
ORWELL_SECRET_BARTER=1
ORWELL_SHOWRUNNER=1
ORWELL_PLAYER_DOSSIER=1
ORWELL_TRAITORS_FURY=1
ORWELL_PRODUCER_READ=1
EOF
}
