import { describe, it, expect } from "vitest";
import { GameSessionAdapter } from "../../src/adapters/engine/GameSessionAdapter";
import type { Campaign } from "../../src/engine/campaigns";
import type { EntityId } from "../../src/domain/ids";

/**
 * Feature 0085 Phase A — the live WIRING: the influence aptitudes are minted on every NPC's CHARACTER
 * (byte-stable, engine-only, never projected), and the campaigns persistence plumbing round-trips. No
 * behavior change yet (campaigns aren't generated by the live engine until Phase B). Roles only.
 */

function started(seed: number): GameSessionAdapter {
  const s = new GameSessionAdapter();
  s.createCharacter({ playerName: "The Player", seed });
  return s;
}

describe("0085 influence traits — minted on the real cast, engine-only", () => {
  it("every houseguest gets persuasiveness + susceptibility in [0,1]", () => {
    const npcs = started(2026).snapshot().house!.npcs;
    for (const n of npcs) {
      const inf = n.character.influence!;
      expect(inf, "influence present").toBeTruthy();
      for (const v of [inf.persuasiveness, inf.susceptibility]) {
        expect(v).toBeGreaterThanOrEqual(0);
        expect(v).toBeLessThanOrEqual(1);
      }
    }
    // The cast is not one uniform value — persuasiveness spreads.
    const ps = npcs.map((n) => n.character.influence!.persuasiveness);
    expect(new Set(ps.map((p) => p.toFixed(2))).size).toBeGreaterThan(3);
  });

  it("influence is byte-stable across a snapshot/restore (static CHARACTER, like the comp stats)", () => {
    const s = started(55);
    const before = s.snapshot().house!.npcs.map((n) => n.character.influence);
    const revived = new GameSessionAdapter();
    revived.restore(s.snapshot());
    expect(revived.snapshot().house!.npcs.map((n) => n.character.influence)).toEqual(before);
  });

  it("influence is NEVER projected to the player (engine-only input, like stats)", () => {
    const s = started(7);
    const id = s.snapshot().house!.npcs[0]!.id;
    const view = s.npcVoice(id);
    const blob = JSON.stringify(view);
    expect(blob).not.toMatch(/persuasiveness|susceptibility/);
  });

  it("same seed ⇒ same influence (deterministic, player-independent)", () => {
    const a = started(404).snapshot().house!.npcs.map((n) => n.character.influence);
    const b = started(404).snapshot().house!.npcs.map((n) => n.character.influence);
    expect(a).toEqual(b);
  });
});

describe("0085 campaigns — persistence plumbing round-trips (Phase A field)", () => {
  it("a live campaign survives a snapshot/restore with its history intact", () => {
    const s = started(88);
    const ids = s.snapshot().house!.npcs.map((n) => n.id);
    const campaign: Campaign = {
      id: "campaign:test", owners: [ids[0]!], goal: "evict", target: ids[1]! as EntityId,
      plan: ["lobby", "plant"], progress: 0.4, horizon: "week", status: "active",
      startedBeat: 2, deadlineBeat: 7, confidence: 0.7, knownTo: [ids[0]!],
    };
    (s as unknown as { campaigns: Campaign[] }).campaigns = [campaign];

    const revived = new GameSessionAdapter();
    revived.restore(s.snapshot());
    const restored = (revived as unknown as { campaigns: Campaign[] }).campaigns;
    expect(restored).toEqual([campaign]);
  });

  it("a campaign never crosses any player-facing seam (Vault-sealed)", () => {
    const s = started(91);
    const ids = s.snapshot().house!.npcs.map((n) => n.id);
    (s as unknown as { campaigns: Campaign[] }).campaigns = [{
      id: "campaign:secret", owners: [ids[0]!], goal: "evict", target: ids[1]!,
      plan: ["lobby"], progress: 0.9, horizon: "week", status: "active",
      startedBeat: 1, deadlineBeat: 6, confidence: 0.9, knownTo: [ids[0]!],
    }];
    // The player-facing reads carry nothing about the campaign.
    const surfaces = JSON.stringify([s.npcVoice(ids[1]!), s.gameStatus(), s.whereabouts()]);
    expect(surfaces).not.toMatch(/campaign:secret|"goal":"evict"/);
  });
});
