import { describe, it, expect } from "vitest";
import {
  generateProducer, producerForSeed, renderProducerVoice,
  validateProducerProfile, mergeProducer, type Producer,
} from "../../src/engine/producerPersona";
import { SeededRandom } from "../../src/adapters/random/SeededRandom";
import { GameSessionAdapter } from "../../src/adapters/engine/GameSessionAdapter";
import { PLAYER } from "../../src/domain/ids";

// The producer persona (producer-persona feature). Roles only (no houseguest names).
//
// The producer is a REAL generated character — as deep a persona as any houseguest, generated by the
// same CharacterFactory machinery — BUT off-camera: no headshot, NOT one of the 16, never in the cast /
// roster / portrait pipeline / whereabouts. Seeded for reproducibility; the casting interview voices it.

describe("the producer is a deep, seeded, off-camera persona", () => {
  it("generates a deep persona (every facet populated, like a houseguest)", () => {
    const p = generateProducer(new SeededRandom(1234));
    // A real character: name, temperament, voice register, strategic disposition, wit, a quirk, backstory.
    expect(p.name.length).toBeGreaterThan(0);
    expect(p.archetype.length).toBeGreaterThan(0);
    expect(p.demeanor.length).toBeGreaterThan(0);
    expect(p.disposition.length).toBeGreaterThan(0);
    expect(p.wit.length).toBeGreaterThan(0);
    expect(p.quirk.length).toBeGreaterThan(0);
    expect(p.backstory.length).toBeGreaterThan(0);
  });

  it("is reproducible by seed and varies across seeds", () => {
    // Same seed → byte-identical producer (a persistent, reproducible persona).
    expect(producerForSeed(99)).toEqual(producerForSeed(99));
    // Across a sweep of seeds the producer is not a constant (a distinct persona per season).
    const signatures = new Set<string>();
    for (let s = 0; s < 40; s++) signatures.add(JSON.stringify(producerForSeed(s)));
    expect(signatures.size).toBeGreaterThan(1);
  });

  it("is structurally off-camera: NO headshot, NOT a houseguest", () => {
    const p = producerForSeed(7);
    expect(p.offCamera).toBe(true);
    expect(p.headshot).toBe(false);
    expect(p.houseguest).toBe(false);
  });

  it("the voice block voices THIS specific producer (facts to voice, never a script)", () => {
    const p = producerForSeed(7);
    const block = renderProducerVoice(p);
    expect(block).toMatch(/WHO YOU ARE/);
    expect(block).toContain(p.name);
    expect(block).toContain(p.disposition);
    expect(block).toContain(p.wit);
    // The wit is framed as DELIBERATE/strategic, never random comedy.
    expect(block).toMatch(/calculated/i);
    expect(block).toMatch(/DELIBERATELY|deliberate/);
  });
});

describe("the producer is voiced in the casting interview, consistently", () => {
  it("the pre-game casting prompt carries the producer's WHO YOU ARE persona block", () => {
    const s = new GameSessionAdapter();
    const prompt = s.getMomentPrompt({}).systemPrompt;
    expect(prompt).toMatch(/WHO YOU ARE/);
    // The block names the SAME producer the engine seeded (the producer's name appears in the prompt).
    const p = producerForSeed(s.snapshot().producerSeed!);
    expect(prompt).toContain(p.name);
  });

  it("the producer is STABLE across turns of the interview (no re-roll per page load)", () => {
    const s = new GameSessionAdapter();
    const first = s.getMomentPrompt({}).systemPrompt;
    const second = s.getMomentPrompt({}).systemPrompt;
    expect(first).toBe(second);
  });

  it("the producer survives a restart (same persona resumes the interview)", () => {
    const s = new GameSessionAdapter();
    s.getMomentPrompt({}); // establish + persist the producer seed
    const seed = s.snapshot().producerSeed;
    expect(seed).toBeDefined();

    const resumed = new GameSessionAdapter();
    resumed.restore(JSON.parse(JSON.stringify(s.snapshot())));
    expect(resumed.snapshot().producerSeed).toBe(seed);
    expect(resumed.getMomentPrompt({}).systemPrompt).toContain(producerForSeed(seed!).name);
  });

  it("the producer voice is present ONLY pre-game, never on an in-house moment", () => {
    const s = new GameSessionAdapter();
    s.createCharacter({ playerName: "The Player", seed: 5 });
    // A live houseguest/host beat is NOT the casting interview — no producer-persona block rides along.
    const prompt = s.getMomentPrompt({ moment: "social" }).systemPrompt;
    expect(prompt).not.toMatch(/WHO YOU ARE \(the producer/);
  });

  it("the casting prompt tells the producer to INTRODUCE THEMSELVES by name first", () => {
    const s = new GameSessionAdapter();
    const prompt = s.getMomentPrompt({}).systemPrompt;
    // The interview opens with the producer naming who they are (the self-introduction beat), before
    // the headshot ask — so the player meets the producer as a person, not a faceless "Production".
    expect(prompt).toMatch(/INTRODUCE YOURSELF FIRST/);
    expect(prompt).toMatch(/naming who you are/);
    // The headshot is no longer the OPENING — it's the first QUESTION after the introduction.
    expect(prompt).toMatch(/YOUR FIRST QUESTION/);
    // ORDER matters: the self-introduction must come BEFORE the first question, or the interview
    // opens on the headshot again (the phrase-presence checks alone can't catch a reordering).
    expect(prompt.indexOf("INTRODUCE YOURSELF FIRST")).toBeLessThan(prompt.indexOf("YOUR FIRST QUESTION"));
  });
});

describe("the producer's public name is exposed for the chat byline (Vault-free)", () => {
  it("getMomentPrompt returns the seeded producer's name as producerName", () => {
    const s = new GameSessionAdapter();
    const view = s.getMomentPrompt({});
    const seededName = producerForSeed(s.snapshot().producerSeed!).name;
    // The byline the FE renders as the chat sender — the SAME producer the prompt voices.
    expect(view.producerName).toBe(seededName);
    expect(view.producerName.length).toBeGreaterThan(0);
  });

  it("producerName is present on EVERY moment (byline is stable across phases), and is stable per season", () => {
    const s = new GameSessionAdapter();
    const preGame = s.getMomentPrompt({}).producerName;
    s.createCharacter({ playerName: "The Player", seed: 5 });
    // The producer persists into the season (adopted seed), so the byline name does not change phase-to-phase.
    const inHouse = s.getMomentPrompt({ moment: "social" }).producerName;
    expect(inHouse).toBe(preGame);
    expect(inHouse.length).toBeGreaterThan(0);
    // Non-degradation (0007): the byline projection survives a save/restore — a resumed session
    // drives the SAME producer name off the restored seed, so the FE byline can never diverge.
    const resumed = new GameSessionAdapter();
    resumed.restore(JSON.parse(JSON.stringify(s.snapshot())));
    expect(resumed.getMomentPrompt({ moment: "social" }).producerName).toBe(preGame);
  });

  it("producerName carries no Vault vocabulary (it is public voice flavor only)", () => {
    const s = new GameSessionAdapter();
    const name = s.getMomentPrompt({}).producerName.toLowerCase();
    // The Vault sentinel sweeps hunt the stat-key substrings; a producer name is a plain given name.
    for (const needle of ["physical", "mental", "social"]) expect(name).not.toContain(needle);
  });
});

// The producer's first NAME is drawn from the same given-name corpus as the cast, so a producer name
// CAN coincide with a houseguest's first name. The exclusion is therefore proven STRUCTURALLY (no
// "producer" id is ever in the house / portraits / a room), never by a fragile name-string absence.
describe("the producer is EXCLUDED from the cast / portraits / whereabouts", () => {
  it("is never one of the 16 houseguests in the roster", () => {
    const s = new GameSessionAdapter();
    s.getMomentPrompt({}); // establish the producer pre-game
    const view = s.createCharacter({ playerName: "The Player", seed: 5 });

    // The cast is exactly the player + 15 NPCs — never 16 NPCs + a producer.
    expect(view.house.length).toBe(15);
    // No roster entry is the off-camera producer (it carries no houseguest id, and is never added).
    expect(view.house.some((h) => h.id === "producer")).toBe(false);
    expect(s.snapshot().house!.npcs.some((n) => n.id === "producer")).toBe(false);
  });

  it("is never in the portrait pipeline (no headshot is ever generated for it)", () => {
    const s = new GameSessionAdapter();
    s.getMomentPrompt({});
    const view = s.createCharacter({ playerName: "The Player", seed: 5 });

    // Exactly one portrait per NPC (the player has no name-hash portrait, #529) — none for the producer.
    expect(view.portraitPrompts!.length).toBe(view.house.length);
    expect(view.portraitPrompts!.some((pp) => pp.houseguestId === "producer")).toBe(false);
    expect(view.portraitPrompts!.some((pp) => pp.houseguestId === "player")).toBe(false);
    // getPortraitPrompt has no entry for a producer id.
    expect(s.getPortraitPrompt("producer" as never)).toBeNull();
  });

  it("is never in the player's whereabouts (off-camera; not in any room)", () => {
    const s = new GameSessionAdapter();
    s.getMomentPrompt({});
    s.createCharacter({ playerName: "The Player", seed: 5 });

    // Every id the whereabouts lists is a real cast member (player + the 15 NPCs) — never a producer.
    const castIds = new Set([PLAYER, ...s.snapshot().house!.npcs.map((n) => n.id)]);
    const wa = s.whereabouts();
    const listed = [
      ...(wa?.present ?? []),
      ...((wa?.nearby ?? []).flatMap((n) => n.present)),
    ];
    for (const ref of listed) expect(castIds.has(ref.id)).toBe(true);
    expect(listed.some((r) => r.id === "producer")).toBe(false);
  });

  it("is never voiceable as a houseguest (no producer entry in the house)", () => {
    const s = new GameSessionAdapter();
    s.getMomentPrompt({});
    s.createCharacter({ playerName: "The Player", seed: 5 });
    // No houseguest carries a producer id — `npcVoice` only resolves real cast ids/names. (The producer's
    // first name is drawn from the same corpus as the cast, so it may COINCIDE with a houseguest's first
    // name; that resolves to that real houseguest, not the producer — the producer itself is never in
    // the house, which the roster/portrait/whereabouts tests above already prove.)
    expect(s.npcVoice("producer" as never)).toBeNull();
    const house = s.snapshot().house!;
    expect(house.npcs.some((n) => n.id === "producer")).toBe(false);
  });
});

describe("the producer carries no Vault content (it is a GM-voice entity)", () => {
  it("the persona is Vault-free public voice flavor — no stats, no hidden vocabulary", () => {
    const block = renderProducerVoice(producerForSeed(13));
    const json = JSON.stringify(producerForSeed(13));
    // No numeric stat / rating ever serializes into the producer or its voice block.
    expect(json).not.toMatch(/\d\.\d/);
    expect(block).not.toMatch(/\d\.\d/);
    // None of the stat-key substrings the Vault sweeps hunt for can serialize from the persona.
    for (const key of ["physical", "mental", "social", "stats", "hiddenElements", "soul"]) {
      expect(json).not.toContain(key);
    }
  });

  it("a producer never holds player-secret material — it knows nothing the cast knows", () => {
    // The producer is generated independently of the cast; it carries no relationship beliefs / souls /
    // hidden elements. (Structural: the Producer type has no such fields — asserted by shape here.)
    const p: Producer = producerForSeed(21);
    expect(p).not.toHaveProperty("hiddenElements");
    expect(p).not.toHaveProperty("soul");
    expect(p).not.toHaveProperty("stats");
    // The player projection is unaffected by the producer (no producer key leaks into the view).
    const s = new GameSessionAdapter();
    s.getMomentPrompt({});
    const view = s.createCharacter({ playerName: "The Player", seed: 5 });
    expect(JSON.stringify(view)).not.toContain("producer");
  });
});

// #1626 increment 3 — the producer can be DEEPENED by an FE-authored overlay (a richer backstory /
// temperament / disposition / wit / quirk) while the seeded NAME stays byte-stable and the persona stays
// Vault-free. Roles only (no houseguest names); the producer is compared only against its own seeded floor.
describe("validateProducerProfile — the open-set / Vault-free authoring envelope (pure)", () => {
  it("accepts open-set prose fields and neutralizes them (whitespace collapsed, length-capped)", () => {
    const { overlay, fields, rejected } = validateProducerProfile({
      backstory: "  ran   the casting desk\nfor years  ",
      wit: "a dry aside before the hard question",
    });
    expect(rejected).toEqual([]);
    expect(fields).toEqual(expect.arrayContaining(["backstory", "wit"]));
    expect(overlay.backstory).toBe("ran the casting desk for years"); // control chars / runs collapsed
  });

  it("IGNORES a proposed name and any unknown key (the byline is seeded and immovable)", () => {
    const { overlay, fields } = validateProducerProfile({ name: "New Name", nonsense: "x", quirk: "keeps a running tally out loud" } as Record<string, unknown>);
    expect(fields).toEqual(["quirk"]);
    expect(overlay).not.toHaveProperty("name");
    expect(overlay).not.toHaveProperty("nonsense");
  });

  it("REJECTS a field carrying stat/soul vocabulary or a decimal rating (Vault-free by construction)", () => {
    for (const bad of ["a keen physical read", "reads mental tells", "a social butterfly", "sees into their soul", "tracks stats", "rated 8.5 of ten"]) {
      const { overlay, fields, rejected } = validateProducerProfile({ disposition: bad });
      expect(fields).toEqual([]);
      expect(rejected).toEqual(["disposition"]);
      expect(overlay).not.toHaveProperty("disposition");
    }
  });

  it("an empty/blank field is NOT a rejection — it simply keeps the seeded floor", () => {
    const { fields, rejected } = validateProducerProfile({ backstory: "   ", wit: "" });
    expect(fields).toEqual([]);
    expect(rejected).toEqual([]); // absent/blank ⇒ floor stands, never a rejection
  });
});

describe("mergeProducer — deepen without degrading (non-degradation)", () => {
  it("with NO overlay the seeded floor stands byte-identical (same reference)", () => {
    const floor = producerForSeed(7);
    expect(mergeProducer(floor, null)).toBe(floor);
    expect(mergeProducer(floor, undefined)).toBe(floor);
  });

  it("the overlay wins where present; the seeded floor fills every omitted field; the NAME stays seeded", () => {
    const floor = producerForSeed(7);
    const merged = mergeProducer(floor, { backstory: "AUTHORED-BACKSTORY: came up through the edit bay" });
    expect(merged.backstory).toBe("AUTHORED-BACKSTORY: came up through the edit bay"); // deepened
    expect(merged.disposition).toBe(floor.disposition); // omitted ⇒ seeded floor preserved (no loss)
    expect(merged.wit).toBe(floor.wit);
    expect(merged.quirk).toBe(floor.quirk);
    expect(merged.name).toBe(floor.name); // byline never churns
    // Structural off-camera flags are immovable.
    expect(merged.offCamera).toBe(true);
    expect(merged.headshot).toBe(false);
    expect(merged.houseguest).toBe(false);
  });

  it("a merged (deepened) producer is still Vault-free — no numeric stat, no hidden vocabulary", () => {
    const merged = mergeProducer(producerForSeed(13), {
      backstory: "ran the desk for a long time and has watched a hundred would-be winners flame out",
      disposition: "casts for the story, not the highlight reel",
    });
    const json = JSON.stringify(merged);
    const block = renderProducerVoice(merged);
    expect(json).not.toMatch(/\d\.\d/);
    expect(block).not.toMatch(/\d\.\d/);
    for (const key of ["physical", "mental", "social", "stats", "hiddenElements", "soul"]) {
      expect(json).not.toContain(key);
    }
  });
});

describe("recordProducerProfile — authoring deepens the persona, persists, and never degrades", () => {
  it("deepens the voiced persona; the seeded name is unchanged and no seeded facet is lost", () => {
    const s = new GameSessionAdapter();
    s.getMomentPrompt({}); // establish the seeded producer
    const seed = s.snapshot().producerSeed!;
    const floor = producerForSeed(seed);

    const res = s.recordProducerProfile({ backstory: "AUTHORED-DEEPENING: crossed over from the edit bay" });
    expect(res.accepted).toBe(true);
    expect(res.fields).toEqual(["backstory"]);

    const prompt = s.getMomentPrompt({}).systemPrompt;
    expect(prompt).toContain("AUTHORED-DEEPENING: crossed over from the edit bay"); // deepened, voiced
    expect(prompt).toContain(floor.disposition); // a NOT-authored seeded facet is still present (no loss)
    expect(s.getMomentPrompt({}).producerName).toBe(floor.name); // byline unchanged
    expect(s.snapshot().producerSeed).toBe(seed); // the seed never moved
  });

  it("ACCUMULATES across authoring calls — a later authoring adds a facet, never loses a prior one", () => {
    const s = new GameSessionAdapter();
    s.getMomentPrompt({});
    expect(s.recordProducerProfile({ backstory: "OVERLAY-BACKSTORY-ONE" }).accepted).toBe(true);
    expect(s.recordProducerProfile({ wit: "OVERLAY-WIT-TWO" }).accepted).toBe(true);
    let prompt = s.getMomentPrompt({}).systemPrompt;
    // BOTH authored facets survive — the second call did not clobber the first.
    expect(prompt).toContain("OVERLAY-BACKSTORY-ONE");
    expect(prompt).toContain("OVERLAY-WIT-TWO");
    // Re-authoring one field REPLACES only it and keeps the accumulated other (deepen, never thin).
    expect(s.recordProducerProfile({ backstory: "OVERLAY-BACKSTORY-THREE" }).accepted).toBe(true);
    prompt = s.getMomentPrompt({}).systemPrompt;
    expect(prompt).toContain("OVERLAY-BACKSTORY-THREE");
    expect(prompt).not.toContain("OVERLAY-BACKSTORY-ONE");
    expect(prompt).toContain("OVERLAY-WIT-TWO"); // accumulated field retained
  });

  it("an empty or all-rejected payload leaves the seeded producer standing (accepted:false)", () => {
    const s = new GameSessionAdapter();
    s.getMomentPrompt({});
    expect(s.recordProducerProfile({})).toEqual({ accepted: false, fields: [], reason: "empty" });
    expect(s.recordProducerProfile({ backstory: "a keen social read" })).toEqual({ accepted: false, fields: [], reason: "rejected" });
    // Nothing folded ⇒ no overlay persists; the seeded floor still voices the interview.
    expect(s.snapshot().producerProfile).toBeUndefined();
    const seed = s.snapshot().producerSeed!;
    expect(s.getMomentPrompt({}).producerName).toBe(producerForSeed(seed).name);
  });

  it("the authored overlay survives a save/restore round-trip (non-degradation, 0007)", () => {
    const s = new GameSessionAdapter();
    s.getMomentPrompt({});
    s.recordProducerProfile({ backstory: "DURABLE-OVERLAY: a chess-opening approach to the room", quirk: "answers a non-answer with a longer silence" });

    const resumed = new GameSessionAdapter();
    resumed.restore(JSON.parse(JSON.stringify(s.snapshot())));
    const prompt = resumed.getMomentPrompt({}).systemPrompt;
    expect(prompt).toContain("DURABLE-OVERLAY: a chess-opening approach to the room");
    expect(prompt).toContain("answers a non-answer with a longer silence");
    // The persisted overlay round-trips field-for-field.
    expect(resumed.snapshot().producerProfile).toEqual(s.snapshot().producerProfile);
    // The byline still tracks the seeded producer after the restore.
    expect(resumed.getMomentPrompt({}).producerName).toBe(producerForSeed(resumed.snapshot().producerSeed!).name);
  });

  it("a deepened producer is STILL excluded from the cast (never one of the 16 / no portrait)", () => {
    const s = new GameSessionAdapter();
    s.getMomentPrompt({});
    s.recordProducerProfile({ backstory: "DEEPENED but still off-camera" });
    const view = s.createCharacter({ playerName: "The Player", seed: 5 });
    expect(view.house.length).toBe(15);
    expect(view.house.some((h) => h.id === "producer")).toBe(false);
    expect(view.portraitPrompts!.some((pp) => pp.houseguestId === "producer")).toBe(false);
  });
});
