import { describe, it, expect } from "vitest";
import {
  generateProducer, producerForSeed, renderProducerVoice, type Producer,
} from "../../src/engine/producerPersona";
import { SeededRandom } from "../../src/adapters/random/SeededRandom";
import { GameSessionAdapter } from "../../src/adapters/engine/GameSessionAdapter";
import { PLAYER } from "../../src/domain/ids";

// The producer persona (producer-persona feature). Roles only (no houseguest names).
//
// The producer is a REAL generated character — as deep a persona as any houseguest, generated by the
// same CharacterFactory machinery — BUT off-camera: no headshot, NOT one of the 16, never in the cast /
// roster / portrait pipeline / whereabouts. Seeded for reproducibility; the casting interview voices it.

describe("the producer is a deep, seeded, off-camera persona", () => {
  it("generates a deep persona (every facet populated, like a houseguest)", () => {
    const p = generateProducer(new SeededRandom(1234));
    // A real character: name, temperament, voice register, strategic disposition, wit, a quirk, backstory.
    expect(p.name.length).toBeGreaterThan(0);
    expect(p.archetype.length).toBeGreaterThan(0);
    expect(p.demeanor.length).toBeGreaterThan(0);
    expect(p.disposition.length).toBeGreaterThan(0);
    expect(p.wit.length).toBeGreaterThan(0);
    expect(p.quirk.length).toBeGreaterThan(0);
    expect(p.backstory.length).toBeGreaterThan(0);
  });

  it("is reproducible by seed and varies across seeds", () => {
    // Same seed → byte-identical producer (a persistent, reproducible persona).
    expect(producerForSeed(99)).toEqual(producerForSeed(99));
    // Across a sweep of seeds the producer is not a constant (a distinct persona per season).
    const signatures = new Set<string>();
    for (let s = 0; s < 40; s++) signatures.add(JSON.stringify(producerForSeed(s)));
    expect(signatures.size).toBeGreaterThan(1);
  });

  it("is structurally off-camera: NO headshot, NOT a houseguest", () => {
    const p = producerForSeed(7);
    expect(p.offCamera).toBe(true);
    expect(p.headshot).toBe(false);
    expect(p.houseguest).toBe(false);
  });

  it("the voice block voices THIS specific producer (facts to voice, never a script)", () => {
    const p = producerForSeed(7);
    const block = renderProducerVoice(p);
    expect(block).toMatch(/WHO YOU ARE/);
    expect(block).toContain(p.name);
    expect(block).toContain(p.disposition);
    expect(block).toContain(p.wit);
    // The wit is framed as DELIBERATE/strategic, never random comedy.
    expect(block).toMatch(/calculated/i);
    expect(block).toMatch(/DELIBERATELY|deliberate/);
  });
});

describe("the producer is voiced in the casting interview, consistently", () => {
  it("the pre-game casting prompt carries the producer's WHO YOU ARE persona block", () => {
    const s = new GameSessionAdapter();
    const prompt = s.getMomentPrompt({}).systemPrompt;
    expect(prompt).toMatch(/WHO YOU ARE/);
    // The block names the SAME producer the engine seeded (the producer's name appears in the prompt).
    const p = producerForSeed(s.snapshot().producerSeed!);
    expect(prompt).toContain(p.name);
  });

  it("the producer is STABLE across turns of the interview (no re-roll per page load)", () => {
    const s = new GameSessionAdapter();
    const first = s.getMomentPrompt({}).systemPrompt;
    const second = s.getMomentPrompt({}).systemPrompt;
    expect(first).toBe(second);
  });

  it("the producer survives a restart (same persona resumes the interview)", () => {
    const s = new GameSessionAdapter();
    s.getMomentPrompt({}); // establish + persist the producer seed
    const seed = s.snapshot().producerSeed;
    expect(seed).toBeDefined();

    const resumed = new GameSessionAdapter();
    resumed.restore(JSON.parse(JSON.stringify(s.snapshot())));
    expect(resumed.snapshot().producerSeed).toBe(seed);
    expect(resumed.getMomentPrompt({}).systemPrompt).toContain(producerForSeed(seed!).name);
  });

  it("the producer voice is present ONLY pre-game, never on an in-house moment", () => {
    const s = new GameSessionAdapter();
    s.createCharacter({ playerName: "The Player", seed: 5 });
    // A live houseguest/host beat is NOT the casting interview — no producer-persona block rides along.
    const prompt = s.getMomentPrompt({ moment: "social" }).systemPrompt;
    expect(prompt).not.toMatch(/WHO YOU ARE \(the producer/);
  });

  it("the casting prompt tells the producer to INTRODUCE THEMSELVES by name first", () => {
    const s = new GameSessionAdapter();
    const prompt = s.getMomentPrompt({}).systemPrompt;
    // The interview opens with the producer naming who they are (the self-introduction beat), before
    // the headshot ask — so the player meets the producer as a person, not a faceless "Production".
    expect(prompt).toMatch(/INTRODUCE YOURSELF FIRST/);
    expect(prompt).toMatch(/naming who you are/);
    // The headshot is no longer the OPENING — it's the first QUESTION after the introduction.
    expect(prompt).toMatch(/THIS IS YOUR FIRST QUESTION/);
  });
});

describe("the producer's public name is exposed for the chat byline (Vault-free)", () => {
  it("getMomentPrompt returns the seeded producer's name as producerName", () => {
    const s = new GameSessionAdapter();
    const view = s.getMomentPrompt({});
    const seededName = producerForSeed(s.snapshot().producerSeed!).name;
    // The byline the FE renders as the chat sender — the SAME producer the prompt voices.
    expect(view.producerName).toBe(seededName);
    expect(view.producerName.length).toBeGreaterThan(0);
  });

  it("producerName is present on EVERY moment (byline is stable across phases), and is stable per season", () => {
    const s = new GameSessionAdapter();
    const preGame = s.getMomentPrompt({}).producerName;
    s.createCharacter({ playerName: "The Player", seed: 5 });
    // The producer persists into the season (adopted seed), so the byline name does not change phase-to-phase.
    const inHouse = s.getMomentPrompt({ moment: "social" }).producerName;
    expect(inHouse).toBe(preGame);
    expect(inHouse.length).toBeGreaterThan(0);
  });

  it("producerName carries no Vault vocabulary (it is public voice flavor only)", () => {
    const s = new GameSessionAdapter();
    const name = s.getMomentPrompt({}).producerName.toLowerCase();
    // The Vault sentinel sweeps hunt the stat-key substrings; a producer name is a plain given name.
    for (const needle of ["physical", "mental", "social"]) expect(name).not.toContain(needle);
  });
});

// The producer's first NAME is drawn from the same given-name corpus as the cast, so a producer name
// CAN coincide with a houseguest's first name. The exclusion is therefore proven STRUCTURALLY (no
// "producer" id is ever in the house / portraits / a room), never by a fragile name-string absence.
describe("the producer is EXCLUDED from the cast / portraits / whereabouts", () => {
  it("is never one of the 16 houseguests in the roster", () => {
    const s = new GameSessionAdapter();
    s.getMomentPrompt({}); // establish the producer pre-game
    const view = s.createCharacter({ playerName: "The Player", seed: 5 });

    // The cast is exactly the player + 15 NPCs — never 16 NPCs + a producer.
    expect(view.house.length).toBe(15);
    // No roster entry is the off-camera producer (it carries no houseguest id, and is never added).
    expect(view.house.some((h) => h.id === "producer")).toBe(false);
    expect(s.snapshot().house!.npcs.some((n) => n.id === "producer")).toBe(false);
  });

  it("is never in the portrait pipeline (no headshot is ever generated for it)", () => {
    const s = new GameSessionAdapter();
    s.getMomentPrompt({});
    const view = s.createCharacter({ playerName: "The Player", seed: 5 });

    // Exactly one portrait per NPC (the player has no name-hash portrait, #529) — none for the producer.
    expect(view.portraitPrompts!.length).toBe(view.house.length);
    expect(view.portraitPrompts!.some((pp) => pp.houseguestId === "producer")).toBe(false);
    expect(view.portraitPrompts!.some((pp) => pp.houseguestId === "player")).toBe(false);
    // getPortraitPrompt has no entry for a producer id.
    expect(s.getPortraitPrompt("producer" as never)).toBeNull();
  });

  it("is never in the player's whereabouts (off-camera; not in any room)", () => {
    const s = new GameSessionAdapter();
    s.getMomentPrompt({});
    s.createCharacter({ playerName: "The Player", seed: 5 });

    // Every id the whereabouts lists is a real cast member (player + the 15 NPCs) — never a producer.
    const castIds = new Set([PLAYER, ...s.snapshot().house!.npcs.map((n) => n.id)]);
    const wa = s.whereabouts();
    const listed = [
      ...(wa?.present ?? []),
      ...((wa?.nearby ?? []).flatMap((n) => n.present)),
    ];
    for (const ref of listed) expect(castIds.has(ref.id)).toBe(true);
    expect(listed.some((r) => r.id === "producer")).toBe(false);
  });

  it("is never voiceable as a houseguest (no producer entry in the house)", () => {
    const s = new GameSessionAdapter();
    s.getMomentPrompt({});
    s.createCharacter({ playerName: "The Player", seed: 5 });
    // No houseguest carries a producer id — `npcVoice` only resolves real cast ids/names. (The producer's
    // first name is drawn from the same corpus as the cast, so it may COINCIDE with a houseguest's first
    // name; that resolves to that real houseguest, not the producer — the producer itself is never in
    // the house, which the roster/portrait/whereabouts tests above already prove.)
    expect(s.npcVoice("producer" as never)).toBeNull();
    const house = s.snapshot().house!;
    expect(house.npcs.some((n) => n.id === "producer")).toBe(false);
  });
});

describe("the producer carries no Vault content (it is a GM-voice entity)", () => {
  it("the persona is Vault-free public voice flavor — no stats, no hidden vocabulary", () => {
    const block = renderProducerVoice(producerForSeed(13));
    const json = JSON.stringify(producerForSeed(13));
    // No numeric stat / rating ever serializes into the producer or its voice block.
    expect(json).not.toMatch(/\d\.\d/);
    expect(block).not.toMatch(/\d\.\d/);
    // None of the stat-key substrings the Vault sweeps hunt for can serialize from the persona.
    for (const key of ["physical", "mental", "social", "stats", "hiddenElements", "soul"]) {
      expect(json).not.toContain(key);
    }
  });

  it("a producer never holds player-secret material — it knows nothing the cast knows", () => {
    // The producer is generated independently of the cast; it carries no relationship beliefs / souls /
    // hidden elements. (Structural: the Producer type has no such fields — asserted by shape here.)
    const p: Producer = producerForSeed(21);
    expect(p).not.toHaveProperty("hiddenElements");
    expect(p).not.toHaveProperty("soul");
    expect(p).not.toHaveProperty("stats");
    // The player projection is unaffected by the producer (no producer key leaks into the view).
    const s = new GameSessionAdapter();
    s.getMomentPrompt({});
    const view = s.createCharacter({ playerName: "The Player", seed: 5 });
    expect(JSON.stringify(view)).not.toContain("producer");
  });
});
